//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bestiary.Properties.Views.MonsterDetailsView {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MonsterDetailsView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MonsterDetailsView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bestiary.Properties.Views.MonsterDetailsView.MonsterDetailsView", typeof(MonsterDetailsView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability Scores.
        /// </summary>
        public static string AbilityScores {
            get {
                return ResourceManager.GetString("AbilityScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to charisma:.
        /// </summary>
        public static string AbilityScores_Charisma {
            get {
                return ResourceManager.GetString("AbilityScores_Charisma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to constitution:.
        /// </summary>
        public static string AbilityScores_Constitution {
            get {
                return ResourceManager.GetString("AbilityScores_Constitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dexterity:.
        /// </summary>
        public static string AbilityScores_Dexterity {
            get {
                return ResourceManager.GetString("AbilityScores_Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intelligence:.
        /// </summary>
        public static string AbilityScores_Intelligence {
            get {
                return ResourceManager.GetString("AbilityScores_Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strength:.
        /// </summary>
        public static string AbilityScores_Strength {
            get {
                return ResourceManager.GetString("AbilityScores_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wisdom:.
        /// </summary>
        public static string AbilityScores_Wisdom {
            get {
                return ResourceManager.GetString("AbilityScores_Wisdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to armor class:.
        /// </summary>
        public static string ArmorClass {
            get {
                return ResourceManager.GetString("ArmorClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at tempor enim, quis dapibus urna. In est lacus, fringilla sit amet molestie dictum, egestas quis neque. Donec mollis consectetur enim, vel iaculis diam fermentum sed. Nam sed elit at purus auctor tempor non sed quam. Praesent quis nunc elementum tellus dictum iaculis id in risus. In eleifend non massa eget ultricies. Aliquam erat volutpat. Phasellus molestie, magna ac hendrerit tincidunt, lorem turpis semper ex, vel fermentum sem sapien ut ips [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hit points:.
        /// </summary>
        public static string HitPoints {
            get {
                return ResourceManager.GetString("HitPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monster.
        /// </summary>
        public static string Monster {
            get {
                return ResourceManager.GetString("Monster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subtype.
        /// </summary>
        public static string Subtype {
            get {
                return ResourceManager.GetString("Subtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP:.
        /// </summary>
        public static string XP {
            get {
                return ResourceManager.GetString("XP", resourceCulture);
            }
        }
    }
}
